name: "PSI Runner"
description: PageSpeed Insights Runner

inputs:
  packages-access-token:
    description: PACKAGES_ACCESS_TOKEN from parent workflow
    required: true
  psi-token:
    description: API key for google PSI
    required: true
  slack-webhook:
    description: slack webhook url
    required: true
  device:
    description: MOBILE or DESKTOP
    required: true
  page-slug:
    description: slug for page to be tested. e.g. /showroom
    required: true

outputs:
  psi:
    description: PSI outputs based on slug and device
    value: ${{ steps.run-psi.outputs.psi-values }}

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install
      run: |
        rm package*
        cd  .github/scripts
        npm i node-fetch@2
      shell: bash
    - name: Run PageSpeed Insights
      id: run-psi
      uses: actions/github-script@v6
      env:
        PAGE_SPEED_INSIGHTS_API_KEY: ${{ inputs.psi-token }}
      with:
        script: |
          const run = require('.github/scripts/psi.js');
          await run({ github, context, core }, { device: "${{ inputs.device }}", slug: "${{ inputs.page-slug}}" });
    - name: Notify Slack
      id: notify
      needs: [run-psi]
      uses: 8398a7/action-slack@v3
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook }}
      with:
        status: custom
        custom_payload: |
          {
            blocks: [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "Categories Page",
                  "emoji": true
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "*URL:* ${{ fromJSON(needs.run-psi.outputs.psi).url }} "
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Device*: Mobile"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*FCP:* ${{ fromJson(needs.run-psi.outputs.psi).FCP}}"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*LCP:* ${{ fromJson(needs.run-psi.outputs.psi).LCP}}"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*TTI:* ${{ fromJson(needs.run-psi.outputs.psi).TTI}}"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*FID:* ${{ fromJson(needs.run-psi.outputs.psi).FID}}"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*CLS:* ${{ fromJson(needs.run-psi.outputs.psi).CLS}}"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*TFB:* ${{ fromJson(needs.run-psi.outputs.psi).TFB}}"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*TBT:* ${{ fromJson(needs.run-psi.outputs.psi).TBT}}"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*SI:* ${{ fromJson(needs.run-psi.outputs.psi).SI}}"
                  }
                ]
              }
            ]
          }
