name: "PSI Runner"
description: PageSpeed Insights Runner

inputs:
  packages-access-token:
    description: PACKAGES_ACCESS_TOKEN from parent workflow
    required: true
  device:
    description: MOBILE or DESKTOP
    required: true
  page-slug:
    description: slug for page to be tested. e.g. /showroom
    required: true

outputs:
  psi:
    description: PSI outputs based on slug and device
    value: ${{ steps.run-psi.outputs.psi-values }}

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install
      uses: actions/setup-node@v3
      run: |
        rm package*
        cd  .github/scripts
        npm i node-fetch@2
      with:
        node-version: 16

    - name: Run PageSpeed Insights
      id: run-psi
      uses: actions/github-script@v6
      env:
        PAGE_SPEED_INSIGHTS_API_KEY: ${{ secrets.PAGE_SPEED_INSIGHTS_API_KEY}}
      with:
        script: |
          const run = require('.github/scripts/psi.js');
          run({ github, context, core }, { device: ${{ inputs.device }}, slug: ${{ inputs.page-slug}} });
